spring.application.name=email-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
server.port=0
spring.mongodb.uri=mongodb://localhost:27017/emailDb
spring.mongodb.representation.uuid=standard

broker.queue.email.name=default.email
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest


spring.mail.host=smtp.gmail.com
pring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}